image: node

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

pages:
  stage: deploy
  script:
    - yarn run build --base=$CI_PAGES_URL
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  only:
    - main
